### ISSUE TITLE
Issue 2: Trong menu start, nếu nhấn bất kì phím nào khác ngoài 1 2 và 3 thì chương trình sẽ kết thúc

### ISSUE THREAD

**Issue by Cheng-23520175** [PhDuy2005/Snake-game#10]

**Comment by Cheng-23520175** [comment]
Issue 2.1: Trong menu choose mode, choose color, choose level, nếu ấn các phím không được lập trình sẵn sẽ quay trở về menu start.

**Comment by Cheng-23520175** [comment]
Đã tạm fix qua pull request #11 

Code tạm nằm ở các dòng: 375, 396, 420, 456, 470

**Comment by PhDuy2005** [comment]
> Đã tạm fix qua pull request #11
> 
> Code tạm nằm ở các dòng: 375, 396, 420, 456, 470

@Cheng-23520175 oke chưa
