### ISSUE TITLE
Lỗi bắt đầu lại game

### ISSUE THREAD

**Issue by PhDuy2005** [PhDuy2005/Snake-game#12]
Nếu game kết thúc bằng Esc -> 2 thì khi bắt đầu lại trò chơi, lập tức nhận thông báo game over (có vẻ chỉ xảy ra sau khi đã ăn được mồi lớn, còn khi chưa ăn được mồi lớn mà Esc->2 thì không gặp lỗi này)

Nếu kết thúc game ở modern mode rồi chuyển sang classic mode thì game cũng kết thúc ngay lập tức

**Comment by Cheng-23520175** [comment]
Đã fix

**Comment by PhDuy2005** [comment]
> Đã fix

uki, cảm ơn m nha
