### ISSUE TITLE
Khi bắt đầu trò chơi chưa khởi tạo đồ ăn

### ISSUE THREAD

**Issue by PhDuy2005** [PhDuy2005/Snake-game#16]
![image](https://github.com/PhDuy2005/Snake-game/assets/94819005/3a400961-4d27-4084-a2f3-4606b3fc87e3)
Khi bắt đầu thì không có đồ ăn (chưa chỉnh mode gì hết nha)
Nếu mà nhấn Esc -> resume thì sẽ hiện đồ ăn

**Comment by Cheng-23520175** [comment]
Fixed trong pr #17
