### ISSUE TITLE
Lỗi bắt đầu lại trò chơi

### ISSUE THREAD

**Issue by PhDuy2005** [PhDuy2005/Snake-game#8]
Sau khi người chơi "chết" và bắt đầu ván chơi mới, màn hình vẫn lưu trạng thái của rắn cũ
@Cheng-23520175

**Comment by PhDuy2005** [comment]
@Cheng-23520175 xong rồi thì m tiến hành close issue nha

**Comment by Cheng-23520175** [comment]
Xong rồi đó, mà m tự close mới đc
@PhDuy2005

**Comment by PhDuy2005** [comment]
Issue này có liên quan đến issue #12
